export const  BlogData = [
    {
      title:"Types of Covid-19 Tests",
      author:"Chloe Kent",
      image: "https://www.medicaldevice-network.com/wp-content/uploads/sites/11/2020/04/shutterstock_1705660609.jpg",
      date:"14th May 2021",
      description:"The three main types of Covid-19 test - PCR, LFT and antibody - all work in different ways to diagnose infection or assess immunity.",
      url:"https://www.medicaldevice-network.com/features/types-of-covid-19-test-antibody-pcr-antigen/",
    },
    {
        title:"Myths Associated with Covid-19",
        author:"Avert.org",
        image: "https://www.avert.org/sites/default/files/styles/responsive_articlecustom_user_desktop_1x/public/COVID-19%20myths.png?itok=F_UHBbVl&timestamp=1587129828",
        date:"30th April 2021",
        description:"We asked our users to share the most common COVID-19 myths and misinformation they have heard. Here we put the record straight.",
        url:"https://www.avert.org/coronavirus/covid-19-myths-and-facts",
      },
      {
        title:"COVID-19 vaccine Efficacy",
        author:"IHME",
        image: "http://www.healthdata.org/sites/default/files/styles/summary_image/public/files/images/coronavirus_2020.jpg",
        date:"4th June 2021",
        description:"The researchers report that the vaccine was equally effective across a variety of different types of people.",
        url:"http://www.healthdata.org/covid/covid-19-vaccine-efficacy-summary",
      },
      {
        title:"Coronavirus disease (COVID-19): Masks",
        author:"WHO",
        image: "https://www2.iqair.com/sites/default/files/inline-images/Masks101_Illustration2.jpg",
        date:"",
        description:"Masks should be used as part of a comprehensive strategy of measures to suppress transmission and save lives.",
        url:"https://www.who.int/news-room/q-a-detail/coronavirus-disease-covid-19-masks",
      },
      {
        title:"Preventing Covid-19",
        author:"CDC",
        image: "https://www.cdc.gov/coronavirus/2019-ncov/images/prevent-getting-sick/neighborhoodBubble-1200x675-large.png",
        date:"8th March 2021",
        description:"The three main types of Covid-19 test - PCR, LFT and antibody - all work in different ways to diagnose infection or assess immunity.",
        url:"https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention.html",
      },
  ];